# Example notebook for the package

Given the RA/DEC (in ANY VALID format), the package will predict the class of the sources in the Field-of-View of the telescope.

The valid formats for RA/DEC are: hhmmss+-ddmmss and degree+-degree

As an example, we have taken three objects. Scroll for more info.
You can search the given objects at: https://simbad.u-strasbg.fr/simbad/sim-fbasic.

`model_file` should contain the path to the trained `.joblib` file. You can either generate this file by running the machine-learning training code "trained_model.ipynb" once or download the post-trained `.joblib` file from Zenodo.

In [1]:
from StellaClass.predict import predict_sdss_coordinates

## SDSS J100554.68+312227.4 -- Quasar

In [ ]:
ra = "10h05m54.678s"
dec = "+31d22m27.476s"
search_radius = 1.0
result = predict_sdss_coordinates(
    ra=ra,
    dec=dec,
    radius_arcsec=search_radius,
    model_file="stellar_class_model.joblib"
)

result

====================================================================================================
SDSS STELLAR-CLASS PREDICTION
====================================================================================================
              objid         ra       dec  separation_arcsec        u        g        r        i        z  redshift predicted_class  confidence_%  P_GALAXY_%  P_QSO_%  P_STAR_%          model_used
1237665129605365783 151.477838 31.374297           0.042075 18.36687 17.99999 17.54177 17.25393 16.83697  1.943719             QSO         89.05       10.44    89.05      0.51 photometry+redshift
1237664336632938539 151.477856 31.374285           0.107338 18.35016 17.96968 17.52185 17.22371 16.87882  1.943719             QSO         90.13        9.26    90.13      0.61 photometry+redshift

Interpretation:
  Match 1: QSO with 89.05% model confidence (GALAXY=10.44%, QSO=89.05%, STAR=0.51%).
  Match 2: QSO with 90.13% model confidence (GALAXY=9.26%, QSO=90.13%, STAR=0.61%).

,objid,ra,dec,u,g,r,i,z,separation_arcsec,redshift,predicted_class,confidence_%,P_GALAXY_%,P_QSO_%,P_STAR_%,model_used,input_warning
0,1237665129605365783,151.477838,31.374297,18.36687,17.99999,17.54177,17.25393,16.83697,0.042075,1.943719,QSO,89.05,10.44,89.05,0.51,photometry+redshift,
1,1237664336632938539,151.477856,31.374285,18.35016,17.96968,17.52185,17.22371,16.87882,0.107338,1.943719,QSO,90.13,9.26,90.13,0.61,photometry+redshift,

## [VV2006] J092653.2+373732 -- Quasar

In [ ]:
ra = "09h26m53.2549s"
dec = "+37d37m32.5018s"
search_radius = 1.0
result = predict_sdss_coordinates(
    ra=ra,
    dec=dec,
    radius_arcsec=search_radius,
    model_file="stellar_class_model.joblib"
)

result

====================================================================================================
SDSS STELLAR-CLASS PREDICTION
====================================================================================================
              objid         ra       dec  separation_arcsec        u        g        r        i        z  redshift predicted_class  confidence_%  P_GALAXY_%  P_QSO_%  P_STAR_%          model_used
1237660342861299735 141.721886 37.625722           0.101318 18.06755 17.97377 17.96225 17.97150 17.88524  2.018758             QSO         100.0         0.0    100.0       0.0 photometry+redshift
1237660342861299734 141.721899 37.625736           0.146934 18.06228 17.96978 17.96036 17.96739 17.89476  2.018758             QSO         100.0         0.0    100.0       0.0 photometry+redshift

Interpretation:
  Match 1: QSO with 100.00% model confidence (GALAXY=0.00%, QSO=100.00%, STAR=0.00%).
  Match 2: QSO with 100.00% model confidence (GALAXY=0.00%, QSO=100.00%, STAR=0.00%).

,objid,ra,dec,u,g,r,i,z,separation_arcsec,redshift,predicted_class,confidence_%,P_GALAXY_%,P_QSO_%,P_STAR_%,model_used,input_warning
0,1237660342861299735,141.721886,37.625722,18.06755,17.97377,17.96225,17.97150,17.88524,0.101318,2.018758,QSO,100.0,0.0,100.0,0.0,photometry+redshift,
1,1237660342861299734,141.721899,37.625736,18.06228,17.96978,17.96036,17.96739,17.89476,0.146934,2.018758,QSO,100.0,0.0,100.0,0.0,photometry+redshift,

## M 82 - Cigar Galaxy

In [ ]:
ra = "09h55m52.430s"
dec = "+69d40m46.93s"
search_radius = 1.0
result = predict_sdss_coordinates(
    ra=ra,
    dec=dec,
    radius_arcsec=search_radius,
    model_file="stellar_class_model.joblib"
)

result

====================================================================================================
SDSS STELLAR-CLASS PREDICTION
====================================================================================================
              objid         ra       dec  separation_arcsec        u        g       r       i        z  redshift predicted_class  confidence_%  P_GALAXY_%  P_QSO_%  P_STAR_% model_used
1237663789038764076 148.968834 69.679743           0.491522 11.70659 10.34703 8.61088 8.11891 7.595294       NaN          GALAXY         94.56       94.56     0.92      4.52 photometry

Interpretation:
  Match 1: GALAXY with 94.56% model confidence (GALAXY=94.56%, QSO=0.92%, STAR=4.52%).

,objid,ra,dec,u,g,r,i,z,separation_arcsec,redshift,predicted_class,confidence_%,P_GALAXY_%,P_QSO_%,P_STAR_%,model_used,input_warning
0,1237663789038764076,148.968834,69.679743,11.70659,10.34703,8.61088,8.11891,7.595294,0.491522,NaN,GALAXY,94.56,94.56,0.92,4.52,photometry,